### ISSUE TITLE
No module named keras.preprocessing

### ISSUE THREAD

**Issue by q2470339** [ijmarshall/robotreviewer#15]
Whenever running this command:

`celery -A robotreviewer.ml_worker worker --loglevel=info`

I get the following message:
```

[INFO] robotreviewer.ml_worker 2017-10-19 01:22:06,140: RobotReviewer machine learning tasks starting
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-19 01:22:06,719: Attempting to start Grobid sever...
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-19 01:22:06,720: Launching Grobid process... (from /Users/.../grobid-grobid-parent-0.4.4)
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-19 01:22:06,727: Success! :)
[DEBUG] robotreviewer.textprocessing.tokenizer 2017-10-19 01:22:06,731: Loading spacy.io data for tokenization
[DEBUG] pip.vcs 2017-10-19 01:22:07,268: Registered VCS backend: git
[DEBUG] pip.vcs 2017-10-19 01:22:07,332: Registered VCS backend: hg
[DEBUG] pip.vcs 2017-10-19 01:22:07,434: Registered VCS backend: svn
[DEBUG] pip.vcs 2017-10-19 01:22:07,436: Registered VCS backend: bzr

Traceback (most recent call last):
  File "/Users/.../miniconda3/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/app/utils.py", line 358, in find_app
    sym = imp(app)
  File "/Users/.../miniconda3/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/Users/.../miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/.../robotreviewer3/robotreviewer/ml_worker.py", line 44, in <module>
    from robotreviewer.robots.rationale_robot import BiasRobot
  File "/Users/.../robotreviewer3/robotreviewer/robots/rationale_robot.py", line 38, in <module>
    from robotreviewer.ml.vectorizer import ModularVectorizer
  File "/Users/.../robotreviewer3/robotreviewer/ml/vectorizer.py", line 19, in <module>
    from keras.preprocessing import sequence
ModuleNotFoundError: No module named 'keras.preprocessing'
```

**Comment by q2470339** [comment]
This error occured due to no keras.json file. Insturctions on how to fix can be seen [here.](https://keras.io/backend/)
