### ISSUE TITLE
Improper config format error

### ISSUE THREAD

**Issue by q2470339** [ijmarshall/robotreviewer#17]
Whenever I try to start the ml worker, I get the following error:

```
Traceback (most recent call last):
  File "/anaconda3/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/anaconda3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/anaconda3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/anaconda3/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/anaconda3/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/anaconda3/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/anaconda3/lib/python3.6/site-packages/celery/app/utils.py", line 358, in find_app
    sym = imp(app)
  File "/anaconda3/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/.../robotreviewer3/robotreviewer/ml_worker.py", line 64, in <module>
    bots = {"bias_bot": BiasRobot(top_k=3),
  File "/Users/.../robotreviewer3/robotreviewer/robots/rationale_robot.py", line 90, in __init__
    document_model_weights_path=weight_loc)
  File "/Users/.../robotreviewer3/robotreviewer/ml/rationale_CNN.py", line 90, in __init__
    self.doc_model = model_from_json(doc_arch_str)
  File "/anaconda3/lib/python3.6/site-packages/keras/models.py", line 345, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2487, in from_config
    process_layer(layer_data)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2473, in process_layer
    custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 100, in from_config
    custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1252, in from_config
    return cls(**config)
  File "/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 812, in __init__
    self.kernel_regularizer = regularizers.get(kernel_regularizer)
  File "/anaconda3/lib/python3.6/site-packages/keras/regularizers.py", line 75, in get
    return deserialize(identifier)
  File "/anaconda3/lib/python3.6/site-packages/keras/regularizers.py", line 68, in deserialize
    printable_module_name='regularizer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 122, in deserialize_keras_object
    raise ValueError('Improper config format: ' + str(config))
ValueError: Improper config format: {'name': 'WeightRegularizer', 'l2': 0.10000000149011612, 'l1': 0.0}
```

**Comment by ijmarshall** [comment]
Sorry for slow response! I wonder if this is a keras version thing — have you used the environment in the repository?

**Comment by ijmarshall** [comment]
no further action, current version working
