### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by poromaa** [ijmarshall/robotreviewer#18]
I have installed this in anaconda env. with . ./setup.sh. I also pip installed the other dependencies (fuzzywuzzy etc) needed, added grobid to config.json path etc, setting Keras to theano.

This is what I get stuck on when trying to start ml_worker:

bash-3.2$ celery -A robotreviewer.ml_worker worker --loglevel=info
[INFO] robotreviewer.ml_worker 2017-10-22 10:46:44,997: RobotReviewer machine learning tasks starting
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-22 10:46:45,094: Attempting to start Grobid sever...
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-22 10:46:45,094: Launching Grobid process... (from /Users/y-/Documents/Scripts/grobid)
[INFO] robotreviewer.textprocessing.pdfreader 2017-10-22 10:46:45,096: Success! :)
[DEBUG] robotreviewer.textprocessing.tokenizer 2017-10-22 10:46:45,097: Loading spacy.io data for tokenization
[DEBUG] pip.vcs 2017-10-22 10:46:45,308: Registered VCS backend: git
[DEBUG] pip.vcs 2017-10-22 10:46:45,320: Registered VCS backend: hg
[DEBUG] pip.vcs 2017-10-22 10:46:45,354: Registered VCS backend: svn
[DEBUG] pip.vcs 2017-10-22 10:46:45,354: Registered VCS backend: bzr
Using Theano backend.
[DEBUG] gensim.models.doc2vec 2017-10-22 10:46:50,526: Fast version of gensim.models.doc2vec is being used
[INFO] summa.preprocessing.cleaner 2017-10-22 10:46:50,533: 'pattern' package not found; tag filters are not available for English
[INFO] robotreviewer.ml_worker 2017-10-22 10:46:50,535: Loading the robots...
Traceback (most recent call last):
  File "/Users/y-/anaconda/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/app/utils.py", line 358, in find_app
    sym = imp(app)
  File "/Users/y-/anaconda/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/Users/y-/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/y-/Documents/Scripts/RB/robotreviewer/ml_worker.py", line 64, in <module>
    bots = {"bias_bot": BiasRobot(top_k=3),
  File "/Users/y-/Documents/Scripts/RB/robotreviewer/robots/rationale_robot.py", line 88, in __init__
    preprocessor = pickle.load(open(vectorizer_loc, 'rb'))
_pickle.UnpicklingError: invalid load key, 'v'.

Any ideas

**Comment by poromaa** [comment]
Might bee that I didn't get the data files (according to closed issue): trying that now. Hopefully that solves it.
git lfs pull   (getting 4.2GB datafiles that I was missing)

**Comment by poromaa** [comment]
Solved with above.

**Comment by eng100200** [comment]
@poromaa  hello, i have the same problem about "_pickle.UnpicklingError: invalid load key, 'v'" , can you discuss how you solved it?

**Comment by raaisakuk** [comment]
@eng100200 I don't know if you were able to resolve the issues. Just type "git lfs pull" in your git repo.
