### ISSUE TITLE
dockfile throws an error (Step 38/42)

### ISSUE THREAD

**Issue by ajoorabchi** [ijmarshall/robotreviewer#25]
**1. encountered this error in the dockfile:**

```
Step 38/42 : RUN cd /var/lib/deploy/robotreviewer/ &&     r.js -o static/build.js &&     mv static static.bak &&     mv build static &&     rm -rf static.bak
 ---> Running in caacf611e66c
Error: Error: /var/lib/deploy/robotreviewer/static/scripts/main.js does not exist.
    at /usr/local/lib/node_modules/requirejs/bin/r.js:29302:27

The command '/bin/sh -c cd /var/lib/deploy/robotreviewer/ &&     r.js -o static/build.js &&     mv static static.bak &&     mv build static &&     rm -rf static.bak' returned a non-zero code: 1
```

**2. comment out "USER deploy" in the doc file:** 

```
# USER deploy
VOLUME /var/lib/deploy/src/robotreviewer/data
# compile client side assets
RUN cd /var/lib/deploy/robotreviewer/ && \
    r.js -o static/build.js && \
    mv static static.bak && \
    mv build static && \
    rm -rf static.bak
```

**this solved the "file not found error" but now another error is thrown:** 

```
Step 37/41 : RUN cd /var/lib/deploy/robotreviewer/ &&     r.js -o static/build.js &&     mv static static.bak &&     mv build static &&     rm -rf static.bak
 ---> Running in 94870ea459c2
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/css/main.css
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/css/report.css
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/scripts/spa/css/foundation.css
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/scripts/spa/css/main.css
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/scripts/spa/css/normalize.css
Optimizing (standard) CSS file: /var/lib/deploy/robotreviewer/build/scripts/spa/css/style.css

Tracing dependencies for: main

Tracing dependencies for: JSXTransformer

Tracing dependencies for: text
Error: Cannot parse file: /var/lib/deploy/robotreviewer/build/build.js for comments. Skipping it. Error is:
Error: Line 19: Unexpected token }
.
.
.
 ---> cd0439f2dcec
Removing intermediate container 94870ea459c2
Step 38/41 : EXPOSE 5000
 ---> Running in c66817511147
 ---> ee7dc309a149
Removing intermediate container c66817511147
Step 39/41 : ENV HOME /var/lib/deploy
 ---> Running in 3a18846e4167
 ---> 43a16c051bfb
Removing intermediate container 3a18846e4167
Step 40/41 : USER root
 ---> Running in e99db339a524
 ---> 8965968677ec
Removing intermediate container e99db339a524
Step 41/41 : ENTRYPOINT /var/lib/deploy/run
 ---> Running in aed5f55ab2b0
 ---> b94fa797d3e0
Removing intermediate container aed5f55ab2b0
Successfully built b94fa797d3e0
```

**below is the docker log:**
```

arash@AJ-780-1:~/Desktop/robotreviewer3-master$ sudo docker logs robotreviewer
Warning: PID file not written; -detached was passed.
[INFO] robotreviewer.app 2018-12-11 21:23:15,413: Welcome to RobotReviewer server :)
[INFO] robotreviewer.ml_worker 2018-12-11 21:23:16,654: RobotReviewer machine learning tasks starting
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'robotreviewer' has no attribute 'ml_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 362, in find_app
    sym = imp(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/deploy/robotreviewer/ml_worker.py", line 38, in <module>
    from robotreviewer.textprocessing.pdfreader import PdfReader
  File "/var/lib/deploy/robotreviewer/textprocessing/pdfreader.py", line 10, in <module>
    from robotreviewer import config
  File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
    export_config(config())
  File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
    return merge_dicts(json_config(), environ_config())
  File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
    with open(path) as p:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
Using Theano backend.
/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[INFO] summarizer.preprocessing.cleaner 2018-12-11 21:23:24,594: 'pattern' package not found; tag filters are not available for English
/var/lib/deploy/robotreviewer/app.py:69: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
[INFO] robotreviewer.app 2018-12-11 21:23:24,661: Loading the robots...
[INFO] robotreviewer.app 2018-12-11 21:23:24,661: Robots loaded successfully! Ready...
[WARNING] robotreviewer.app 2018-12-11 21:23:24,664: Could not start scheduled clean-up task
arash@AJ-780-1:~/Desktop/robotreviewer3-master$ sudo docker logs robotreviewer
Warning: PID file not written; -detached was passed.
[INFO] robotreviewer.app 2018-12-11 21:23:15,413: Welcome to RobotReviewer server :)
[INFO] robotreviewer.ml_worker 2018-12-11 21:23:16,654: RobotReviewer machine learning tasks starting
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'robotreviewer' has no attribute 'ml_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 362, in find_app
    sym = imp(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/deploy/robotreviewer/ml_worker.py", line 38, in <module>
    from robotreviewer.textprocessing.pdfreader import PdfReader
  File "/var/lib/deploy/robotreviewer/textprocessing/pdfreader.py", line 10, in <module>
    from robotreviewer import config
  File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
    export_config(config())
  File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
    return merge_dicts(json_config(), environ_config())
  File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
    with open(path) as p:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
Using Theano backend.
/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[INFO] summarizer.preprocessing.cleaner 2018-12-11 21:23:24,594: 'pattern' package not found; tag filters are not available for English
/var/lib/deploy/robotreviewer/app.py:69: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
[INFO] robotreviewer.app 2018-12-11 21:23:24,661: Loading the robots...
[INFO] robotreviewer.app 2018-12-11 21:23:24,661: Robots loaded successfully! Ready...
[WARNING] robotreviewer.app 2018-12-11 21:23:24,664: Could not start scheduled clean-up task
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET / HTTP/1.1" 200 2090 0.016438
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /css/main.css HTTP/1.1" 200 176417 0.016441
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /css/report.css HTTP/1.1" 200 1911 0.002908
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /scripts/modernizr.js HTTP/1.1" 200 11472 0.001443
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /scripts/spa/scripts/vendor/pdfjs/pdf.js HTTP/1.1" 200 142180 0.002863
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /scripts/spa/scripts/vendor/compatibility.js HTTP/1.1" 200 8238 0.001442
::ffff:172.17.0.1 - - [2018-12-11 21:26:02] "GET /scripts/require.js HTTP/1.1" 200 15385 0.002254
::ffff:172.17.0.1 - - [2018-12-11 21:26:03] "GET /img/logo.svg HTTP/1.1" 200 77727 0.003689
[ERROR] flask.app 2018-12-11 21:26:03,359: Exception on /report_view/Tvg0-pHV2QBsYpJxE2KW-/html [GET]
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/deploy/robotreviewer/app.py", line 157, in report_view
    return produce_report(report_uuid, format, download=False)
  File "/var/lib/deploy/robotreviewer/app.py", line 188, in produce_report
    for i, row in enumerate(c.execute("SELECT pdf_uuid, annotations FROM article WHERE report_uuid=?", (report_uuid,))):
sqlite3.DatabaseError: file is not a database
::ffff:172.17.0.1 - - [2018-12-11 21:26:03] "GET /report_view/Tvg0-pHV2QBsYpJxE2KW-/html HTTP/1.1" 500 412 0.023783
[ERROR] flask.app 2018-12-11 21:26:03,361: Exception on /report_view/_fzGUEvWAeRsqYSmNQbBq/html [GET]
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/deploy/robotreviewer/app.py", line 157, in report_view
    return produce_report(report_uuid, format, download=False)
  File "/var/lib/deploy/robotreviewer/app.py", line 188, in produce_report
    for i, row in enumerate(c.execute("SELECT pdf_uuid, annotations FROM article WHERE report_uuid=?", (report_uuid,))):
sqlite3.DatabaseError: file is not a database
::ffff:172.17.0.1 - - [2018-12-11 21:26:03] "GET /report_view/_fzGUEvWAeRsqYSmNQbBq/html HTTP/1.1" 500 412 0.001590
[ERROR] flask.app 2018-12-11 21:26:03,383: Exception on /report_view/HBkzX1I3Uz_kZEQYeqXJf/html [GET]
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/deploy/robotreviewer/app.py", line 157, in report_view
    return produce_report(report_uuid, format, download=False)
  File "/var/lib/deploy/robotreviewer/app.py", line 188, in produce_report
    for i, row in enumerate(c.execute("SELECT pdf_uuid, annotations FROM article WHERE report_uuid=?", (report_uuid,))):
sqlite3.DatabaseError: file is not a database
::ffff:172.17.0.1 - - [2018-12-11 21:26:03] "GET /report_view/HBkzX1I3Uz_kZEQYeqXJf/html HTTP/1.1" 500 412 0.001663
::ffff:172.17.0.1 - - [2018-12-11 21:26:03] "GET /scripts/main.js HTTP/1.1" 200 372669 0.003199
::ffff:172.17.0.1 - - [2018-12-11 21:26:04] "GET /img/infinity.gif HTTP/1.1" 200 53443 0.001551
::ffff:172.17.0.1 - - [2018-12-11 21:26:04] "GET /favicon.ico HTTP/1.1" 404 342 0.002453
[ERROR] flask.app 2018-12-11 21:26:18,111: Exception on /upload_and_annotate [POST]
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/deploy/robotreviewer/app.py", line 126, in upload_and_annotate
    c.execute("INSERT INTO doc_queue (report_uuid, pdf_uuid, pdf_hash, pdf_filename, pdf_file, timestamp) VALUES (?, ?, ?, ?, ?, ?)", (report_uuid, pdf_uuid, pdf_hash, filename, sqlite3.Binary(blob), datetime.now()))
sqlite3.DatabaseError: file is not a database
```

**Comment by dharbinjaep** [comment]
Were you able to find a fix for this? I'm seeing the same issue.

**Comment by ijmarshall** [comment]
Are the issues above solved by following your instructions in [your other issue](https://github.com/ijmarshall/robotreviewer3/issues/32#issuecomment-486695780)?
