### ISSUE TITLE
docker build failed at step 41

### ISSUE THREAD

**Issue by ajoorabchi** [ijmarshall/robotreviewer#32]
Step 33/45 : USER root
 ---> Running in 7823882bd3a4
Removing intermediate container 7823882bd3a4
 ---> 596ac2336787
Step 34/45 : RUN mkdir -p /var/lib/deploy/robotreviewer/data
 ---> Running in 5a7edc6d85de
Removing intermediate container 5a7edc6d85de
 ---> da724724a4d5
Step 35/45 : ADD server.py /var/lib/deploy/
 ---> 664ea4834eb2
Step 36/45 : ADD run /var/lib/deploy/
 ---> 7fae45ce5ab8
Step 37/45 : ADD robotreviewer /var/lib/deploy/robotreviewer
 ---> 882f12643e64
Step 38/45 : RUN chown -R deploy.deploy /var/lib/deploy/robotreviewer
 ---> Running in f517507c9d13
Removing intermediate container f517507c9d13
 ---> bfee772d72d9
Step 39/45 : USER deploy
 ---> Running in 57ca5b5c1d0c
Removing intermediate container 57ca5b5c1d0c
 ---> 5a7b422f7dae
Step 40/45 : VOLUME /var/lib/deploy/src/robotreviewer/data
 ---> Running in 3c4cacf4524f
Removing intermediate container 3c4cacf4524f
 ---> f74e3345385e
Step 41/45 : RUN cd /var/lib/deploy/robotreviewer/ &&     r.js -o static/build.js &&     mv static static.bak &&     mv build static &&     rm -rf static.bak
 ---> Running in a54797dc970f
Error: Error: /var/lib/deploy/robotreviewer/static/scripts/main.js does not exist.
    at /usr/local/lib/node_modules/requirejs/bin/r.js:29302:27

The command '/bin/sh -c cd /var/lib/deploy/robotreviewer/ &&     r.js -o static/build.js &&     mv static static.bak &&     mv build static &&     rm -rf static.bak' returned a non-zero code: 1

**Comment by h21k** [comment]
hm looks like when you build your docker container it can not find the files to copy to the respective folder in the container. Perhaps run the script again? What branch are you using? Also are you scripting runs or did you follow the main instructions?

**Comment by ajoorabchi** [comment]
Thank you; these are the steps I am taking:

1. git clone -b master --single-branch https://github.com/ijmarshall/robotreviewer3.git
2. cd robotreviewer3 ; git status

> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working directory clean

 3.  sudo docker build -t robotreviewer .

> .
> .
> .
> Step 45/45 : ENTRYPOINT ["/var/lib/deploy/run"]
>  ---> Running in 515319a02099
> Removing intermediate container 515319a02099
>  ---> a139656dd41d
> Successfully built a139656dd41d
> Successfully tagged robotreviewer:latest

4. sudo ./start.sh

> 96d33726f75837c4385ab217983b1944f31ec90379f45452288769535400d77a

however, the server(http://localhost:5050/) is not reachable and the container log shows the following errors:
```
sudo docker logs robotreviewer
Warning: PID file not written; -detached was passed.
Traceback (most recent call last):
  File "/var/lib/deploy/server.py", line 2, in <module>
    from robotreviewer import config
  File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
    export_config(config())
  File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
    return merge_dicts(json_config(), environ_config())
  File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
    with open(path) as p:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'robotreviewer' has no attribute 'ml_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 362, in find_app
    sym = imp(app)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/deploy/robotreviewer/ml_worker.py", line 32, in <module>
    from robotreviewer import config
  File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
    export_config(config())
  File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
    return merge_dicts(json_config(), environ_config())
  File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
    with open(path) as p:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
```


[build_log.txt](https://github.com/ijmarshall/robotreviewer3/files/3117440/build_log.txt)

**Comment by ijmarshall** [comment]
There is a requirement for a config.json file (described in the README).

If you copy robotreviewer/config.json.example to robotreviewer/config.json it should work.

In fact if using Docker, the contents don't matter so long as its valid JSON (so you can just copy the example one exactly without edits). I will fix up the README to make this clearer.

**Comment by ajoorabchi** [comment]
Thank you, creating robotreviewer/config.json resolved that issue, and the container seems to be running error free now:

> sudo docker logs robotreviewer
> Warning: PID file not written; -detached was passed.
> [INFO] robotreviewer.app 2019-04-25 19:15:59,922: Welcome to RobotReviewer server :)
> 2019-04-25 19:16:01.677884: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.
> 2019-04-25 19:16:04.141752: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.

However, the website is still not reachable:

```
(base) arash@AJ-780-1:~/Desktop/robotreviewer3$ sudo docker container ls 
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS                      NAMES
b3321393ad69        robotreviewer       "/var/lib/deploy/run"   2 hours ago         Up About an hour    127.0.0.1:5050->5000/tcp   robotreviewer

(base) arash@AJ-780-1:~/Desktop/robotreviewer3$ nmap -p 5050 localhost

Starting Nmap 7.01 ( https://nmap.org ) at 2019-04-25 21:58 IST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00012s latency).
PORT     STATE SERVICE
5050/tcp open  mmcc

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds

(base) arash@AJ-780-1:~/Desktop/robotreviewer3$ wget http://localhost:5050
--2019-04-25 21:58:32--  http://localhost:5050/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5050... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-04-25 21:58:33--  (try: 2)  http://localhost:5050/
Connecting to localhost (localhost)|127.0.0.1|:5050... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.


```
