### ISSUE TITLE
unknown opcode (theano version issue ? )

### ISSUE THREAD

**Issue by yinfeiy** [ijmarshall/robotreviewer#4]
Hi 

I am trying to run robotreviewer, but got following error message: 

[INFO] robotreviewer.app 2017-07-25 21:51:12,107: Loading the robots

```
...
loading model architecture from file: robotreviewer/data/keras/models/RSG.json
XXX lineno: 343, opcode: 0
Traceback (most recent call last):
  File "/mnt/data/bin/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/data/bin/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/workspace/nlp/robotreviewer3/robotreviewer/__main__.py", line 1, in <module>
    from robotreviewer import app
  File "/mnt/data/workspace/nlp/robotreviewer3/robotreviewer/app.py", line 84, in <module>
    bots = {"bias_bot": BiasRobot(top_k=3),
  File "/mnt/data/workspace/nlp/robotreviewer3/robotreviewer/robots/rationale_robot.py", line 90, in __init__
    document_model_weights_path=weight_loc)
  File "robotreviewer/ml/rationale_CNN.py", line 90, in __init__
    self.doc_model = model_from_json(doc_arch_str)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/models.py", line 213, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/utils/layer_utils.py", line 40, in layer_from_config
    custom_objects=custom_objects)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2582, in from_config
    process_layer(layer_data)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2577, in process_layer
    layer(input_tensors[0])
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 126, in call
    y = self.layer.call(inputs)  # (nb_samples * timesteps, ...)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 641, in call
    return self.function(x, **arguments)
  File "/home/ubuntu/rationale-CNN/rationale_CNN.py", line 343, in <lambda>
    sw_layer = Lambda(lambda x: K.max(x[:,0:2], axis=1), output_shape=(1,))
SystemError: unknown opcode
```

I had another issue before, that:
```
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 111, in call
    x = K.in_train_phase(dropped_inputs, lambda: x)
  File "/mnt/data/bin/anaconda3/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 1176, in in_train_phase
    x = ifelse.ifelse(_LEARNING_PHASE, x, alt)
AttributeError: 'function' object has no attribute 'ifelse'
```

This error can be solved by adding:
import theano.ifelse
from theano.ifelse import IfElse, ifelse
at the beginning of the theano_backend.py. But it may indicates the theano version may matters. 

My theano version is 0.10.0.dev1, keras version 1.2.2

Any idea how to fix this ? Or what is the working version of theano ?

Thanks
Yinfei

**Comment by yinfeiy** [comment]
Switching to anconda 3.4.2 solved the problem. This version of anconda is with python3.5
The anconda 3.4.4 with python3.6 shows the error above.

**Comment by bwallace** [comment]
thanks, @yinfeiy!
