### ISSUE TITLE
Error when running docker-compose

### ISSUE THREAD

**Issue by lucianosilvi** [ijmarshall/robotreviewer#47]
Hi, when following the steps to build and up the docker-compose.yml, I get the following error in the logs, is there any issue in the code itself?
Thanks

```
celery_1    | [entrypoint.sh] Starting Celery
celery_1    | /var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
celery_1    |   warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
celery_1    | Traceback (most recent call last):
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 373, in find_app
celery_1    |     sym = symbol_by_name(app, imp=imp)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 534, in symbol_by_name
celery_1    |     return imports.symbol_by_name(name, imp=imp)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/kombu/utils/imports.py", line 62, in symbol_by_name
celery_1    |     return getattr(module, cls_name) if cls_name else module
celery_1    | AttributeError: module 'robotreviewer' has no attribute 'ml_worker'
celery_1    | 
celery_1    | During handling of the above exception, another exception occurred:
celery_1    | 
celery_1    | Traceback (most recent call last):
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/bin/celery", line 8, in <module>
celery_1    |     sys.exit(main())
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_1    |     _main()
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_1    |     cmd.execute_from_commandline(argv)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
celery_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
celery_1    |     argv = self.setup_app_from_commandline(argv)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
celery_1    |     self.app = self.find_app(app)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/bin/base.py", line 531, in find_app
celery_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/app/utils.py", line 376, in find_app
celery_1    |     sym = imp(app)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
celery_1    |     return imp(module, package=package)
celery_1    |   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
celery_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
celery_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
celery_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celery_1    |   File "/var/lib/deploy/robotreviewer/ml_worker.py", line 52, in <module>
celery_1    |     from robotreviewer.robots.pico_span_robot import PICOSpanRobot
celery_1    |   File "/var/lib/deploy/robotreviewer/robots/pico_span_robot.py", line 32, in <module>
celery_1    |     from robotreviewer.textprocessing import minimap
celery_1    |   File "/var/lib/deploy/robotreviewer/textprocessing/minimap.py", line 21, in <module>
celery_1    |     str_to_cui = pickle.load(f)
celery_1    | _pickle.UnpicklingError: invalid load key, 'v'.

```

**Comment by rileygreen022** [comment]
It is because the larger files are not being pulled.

"git lfs pull    
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

A quick work around is: 
https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh
