### ISSUE TITLE
Pickling error when running 

### ISSUE THREAD

**Issue by jdoedoej** [ijmarshall/robotreviewer#5]
I have followed all of the instructions to install (including git-lfs + Keras has been set to use theano) but upon running RR3 I receive this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.../robotreviewer3/robotreviewer/__main__.py", line 1, in <module>
    from robotreviewer import app
  File "/home/.../robotreviewer3/robotreviewer/app.py", line 85, in <module>
    bots = {"bias_bot": BiasRobot(top_k=3),
  File "/home/.../robotreviewer3/robotreviewer/robots/rationale_robot.py", line 87, in __init__
    preprocessor = pickle.load(open(vectorizer_loc, 'rb'))
_pickle.UnpicklingError: invalid load key, 'v'.
```
Any ideas on how to fix?

**Comment by ijmarshall** [comment]
It looks like you might not have the full data file. Could you try running `git lfs pull` and see if this fixes it?

**Comment by jdoedoej** [comment]
Thanks this worked. However when I now run it this is printed to the terminal:

```
[INFO] robotreviewer.app 2017-09-03 14:59:33,678: Loading the robots...
loading model architecture from file: robotreviewer/data/keras/models/RSG.json
ok!
Killed

```

Any ideas on why it is killed?
